GET http://localhost:3000/jogadores

GET http://localhost:3000/jogadores/1

GET http://localhost:3000/jogadores/999

POST http://localhost:3000/jogadores
Content-Type: application/json

{
  "nome": "Vinicius Jr",
  "time": "Real Madrid",
  "posicao": "Atacante"
}

PUT http://localhost:3000/jogadores/2
Content-Type: application/json

{
  "time": "Barcelona",
  "posicao": "Meia"
}

### Deletar
DELETE http://localhost:3000/jogadores/1